// The spec generator: reads spec/enums.h, spec/ops.h and spec/draw.h (the X-macro tables) and emits
// the same values for TypeScript, Kotlin and Swift into spec/gen/. Run `bun spec/generate.ts`
// after a spec edit; `bun spec/generate.ts --check` fails when the committed files are stale (CI).
//
// The headers stay the single source: nothing here knows what an opcode means, only its name, id and
// operand layout.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"

const specDir = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"))
const genDir = join(specDir, "gen")

interface EnumDef { name: string, members: { name: string, value: number }[] }
interface OpDef { name: string, id: number, args: string, repeat: string, doc: string }
interface DrawDef { name: string, id: number, doc: string }

// ---- parsing the headers --------------------------------------------------------------------

const read = (f: string) => readFileSync(join(specDir, f), "utf8")

const parseEnums = (src: string): EnumDef[] => {
  // The order of ANYCANVAS_ENUMS(E) is the order of the emitted enums.
  const listAt = src.indexOf("#define ANYCANVAS_ENUMS(E)")
  if (listAt < 0) throw new Error("ANYCANVAS_ENUMS not found")
  const order = [...src.slice(listAt).matchAll(/E\((\w+),\s*(ANYCANVAS_ENUM_\w+)\)/g)].map(m => ({ name: m[1], macro: m[2] }))
  return order.map(({ name, macro }) => {
    const m = src.match(new RegExp(`#define ${macro}\\(X\\)([\\s\\S]*?)\\n\\n`))
    if (!m) throw new Error(`enum macro ${macro} not found`)
    const members = [...m[1].matchAll(/X\((\w+),\s*(\d+)\)/g)].map(x => ({ name: x[1], value: Number(x[2]) }))
    return { name, members }
  })
}

const parseOps = (src: string): OpDef[] =>
  [...src.matchAll(/X\((\w+),\s*(\d+),\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)"\)/g)]
    .map(m => ({ name: m[1], id: Number(m[2]), args: m[3], repeat: m[4], doc: m[5] }))

const parseDraw = (src: string): DrawDef[] =>
  [...src.matchAll(/X\((\w+),\s*(\d+),\s*"([^"]*)"\)/g)]
    .map(m => ({ name: m[1], id: Number(m[2]), doc: m[3] }))

const parseVersion = (src: string): number => {
  const m = src.match(/#define ANYCANVAS_SPEC_VERSION (\d+)/)
  if (!m) throw new Error("ANYCANVAS_SPEC_VERSION not found")
  return Number(m[1])
}

const checkUnique = (what: string, items: { name: string, id?: number, value?: number }[]) => {
  const ids = new Set<number>()
  for (const it of items) {
    const id = it.id ?? it.value!
    if (ids.has(id)) throw new Error(`${what}: duplicate id ${id} (${it.name})`)
    ids.add(id)
  }
}

// ---- emitters ---------------------------------------------------------------------------------

const HEADER = "GENERATED by spec/generate.ts from spec/*.h — do not edit."

const camel = (s: string) => s.toLowerCase().replace(/_(\w)/g, (_, c: string) => c.toUpperCase())
const pascal = (s: string) => { const c = camel(s); return c[0].toUpperCase() + c.slice(1) }
const lowerName = (s: string) => s.toLowerCase().replace(/_/g, "")

const emitTs = (version: number, enums: EnumDef[], ops: OpDef[], draw: DrawDef[]): string => {
  const out: string[] = [`// ${HEADER}`, "", `export const SPEC_VERSION = ${version}`, ""]
  for (const e of enums) {
    out.push(`export const ${e.name} = {`)
    for (const m of e.members) out.push(`  ${m.name}: ${m.value},`)
    out.push(`} as const`)
    out.push(`export type ${e.name} = (typeof ${e.name})[keyof typeof ${e.name}]`)
    // The wire value → its lowercase name (the JSON dump and the painters' string maps).
    out.push(`export const ${e.name}Name: readonly string[] = [${e.members.map(m => JSON.stringify(m.name.toLowerCase())).join(", ")}]`)
    out.push("")
  }
  out.push("/** The opcode stream: op id → the word after it. */")
  out.push("export const OP = {")
  for (const o of ops) out.push(`  ${o.name}: ${o.id},`)
  out.push("} as const")
  out.push("export type OP = (typeof OP)[keyof typeof OP]")
  out.push("/** Operand layout per op: `args` is one letter per fixed word (f float, i int, r string ref);")
  out.push(" *  `repeat` is the group that follows the trailing count. */")
  out.push("export const OP_ARGS: Record<number, { args: string, repeat: string }> = {")
  for (const o of ops) out.push(`  ${o.id}: { args: ${JSON.stringify(o.args)}, repeat: ${JSON.stringify(o.repeat)} },`)
  out.push("}")
  out.push(`export const OP_NAME: readonly string[] = [${ops.map(o => JSON.stringify(camel(o.name))).join(", ")}]`)
  out.push("")
  out.push("/** The draw list: command id → the word after it. */")
  out.push("export const DRAW = {")
  for (const d of draw) out.push(`  ${d.name}: ${d.id},`)
  out.push("} as const")
  out.push("export type DRAW = (typeof DRAW)[keyof typeof DRAW]")
  out.push(`export const DRAW_NAME: readonly string[] = [${draw.map(d => JSON.stringify(camel(d.name))).join(", ")}]`)
  out.push("")
  return out.join("\n")
}

const emitKotlin = (version: number, enums: EnumDef[], ops: OpDef[], draw: DrawDef[]): string => {
  const out: string[] = [`// ${HEADER}`, "package io.letary.anycanvas.spec", "", `const val SPEC_VERSION = ${version}`, ""]
  for (const e of enums) {
    out.push(`enum class ${e.name}(val id: Int) {`)
    out.push(e.members.map(m => `    ${m.name}(${m.value})`).join(",\n") + ";")
    out.push("")
    out.push(`    companion object {`)
    out.push(`        private val byId = entries.associateBy { it.id }`)
    out.push(`        fun of(id: Int): ${e.name} = byId[id] ?: throw IllegalArgumentException("${e.name}: unknown id $id")`)
    out.push(`    }`)
    out.push("}")
    out.push("")
  }
  out.push("/** The opcode stream: op id → the word after it. */")
  out.push("object Op {")
  for (const o of ops) out.push(`    const val ${o.name} = ${o.id}`)
  out.push("}")
  out.push("")
  out.push("/** The draw list commands. A painter switches over this enum exhaustively. */")
  out.push("enum class DrawCmd(val id: Int) {")
  out.push(draw.map(d => `    ${d.name}(${d.id})`).join(",\n") + ";")
  out.push("")
  out.push("    companion object {")
  out.push("        private val byId = entries.associateBy { it.id }")
  out.push("        /** null for a command this build does not know (the painter skips `len` words). */")
  out.push("        fun of(id: Int): DrawCmd? = byId[id]")
  out.push("    }")
  out.push("}")
  out.push("")
  return out.join("\n")
}

const emitSwift = (version: number, enums: EnumDef[], ops: OpDef[], draw: DrawDef[]): string => {
  const out: string[] = [`// ${HEADER}`, "", `public let specVersion: Int32 = ${version}`, ""]
  for (const e of enums) {
    out.push(`public enum ${e.name}: Int32 {`)
    for (const m of e.members) out.push(`    case ${swiftCase(m.name)} = ${m.value}`)
    out.push("}")
    out.push("")
  }
  out.push("/// The opcode stream: op id → the word after it.")
  out.push("public enum Op: Int32 {")
  for (const o of ops) out.push(`    case ${swiftCase(o.name)} = ${o.id}`)
  out.push("}")
  out.push("")
  out.push("/// The draw list commands. A painter switches over this enum exhaustively.")
  out.push("public enum DrawCmd: Int32 {")
  for (const d of draw) out.push(`    case ${swiftCase(d.name)} = ${d.id}`)
  out.push("}")
  out.push("")
  return out.join("\n")
}

const SWIFT_KEYWORDS = new Set(["repeat", "default", "in", "is", "as", "do", "if", "for", "case", "none"])
const swiftCase = (name: string) => { const c = camel(name); return SWIFT_KEYWORDS.has(c) ? "`" + c + "`" : c }

// ---- main ---------------------------------------------------------------------------------------

const enumsSrc = read("enums.h"), opsSrc = read("ops.h"), drawSrc = read("draw.h")
const enums = parseEnums(enumsSrc), ops = parseOps(opsSrc), draw = parseDraw(drawSrc)
const version = parseVersion(opsSrc)
if (ops.length === 0 || draw.length === 0 || enums.length === 0) throw new Error("spec tables came out empty — the header format changed?")
checkUnique("ops", ops); checkUnique("draw", draw)
for (const e of enums) checkUnique(e.name, e.members)

const files: Record<string, string> = {
  "spec.ts": emitTs(version, enums, ops, draw),
  "Spec.kt": emitKotlin(version, enums, ops, draw),
  "Spec.swift": emitSwift(version, enums, ops, draw),
}

const check = process.argv.includes("--check")
let stale = 0
if (!existsSync(genDir)) mkdirSync(genDir, { recursive: true })
for (const [name, content] of Object.entries(files)) {
  const path = join(genDir, name)
  const current = existsSync(path) ? readFileSync(path, "utf8") : null
  if (current === content) continue
  if (check) { console.error(`stale: spec/gen/${name} (run bun spec/generate.ts)`); stale++ }
  else { writeFileSync(path, content); console.log(`wrote spec/gen/${name}`) }
}
if (stale) process.exit(1)
if (check) console.log(`spec/gen is fresh (${ops.length} ops, ${draw.length} draw commands, ${enums.length} enums, version ${version})`)
void lowerName; void pascal
